### ISSUE TITLE
Failed to compile on CentOS 8.1 x64

### ISSUE THREAD

**Issue by trippleflux** [greenplum-db/gpdb#10047]
### Greenplum version or build
Current git master branch

### OS version and uname -a
CentOS 8.1 x64
Linux localhost.localdomain 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
./configure --with-perl --with-python --with-libxml --with-gssapi --prefix=/usr/local/gpdb

### Expected behavior
Able to comple until finish

### Actual behavior
Error while compiling, for example the error : 
/usr/include/xercesc/sax2/DefaultHandler.hpp:800:54: error: ‘XMLCh’ does not name a type; did you mean ‘XMLUni’?
Complete compilation log : [compile.log](https://github.com/greenplum-db/gpdb/files/4571644/compile.log)

xerces-c.x86_64                      3.2.2-3.el8                           @epel        
xerces-c-devel.x86_64                3.2.2-3.el8                           @epel    

### Step to reproduce the behavior

Try to compile in CentOS 8.1 x64

**Comment by Eulerizeit** [comment]
This is expected until we make it so that Orca can compile with C++14. In the following Closed PR there is a todo list in the final comment. If you'd like to help please jump on one of those PRs. 

https://github.com/greenplum-db/gpdb/pull/9937

**Comment by parisni** [comment]
hello. I am experiencing the same issue on debian 10 with gpdb 6.12.1 source

**Comment by kainwen** [comment]
> hello. I am experiencing the same issue on debian 10 with gpdb 6.12.1 source

maybe the version of Xerces is too new for gp6.

**Comment by parisni** [comment]
thanks for your help.

Indeed, debian 10 provides libxerces 3.2.2.
I downloaded the 3.1.1 version, compiled and installed it, while removing the newer version.
all went fine with gdp6 on debian 10 .

gpd7 (master branch) is ok with xerces 3.2 BTW
