### PR TITLE
Fix uninitialized variable in pgrowlocks

### PR DESCRIPTION
**Pull request by japinli**
I encounter the following When I build master branch on Ubuntu 16.04 with gcc 6.3.0.

```
pgrowlocks.c: In function ‘pgrowlocks’:
pgrowlocks.c:132:8: error: ‘rel’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   htsu = HeapTupleSatisfiesUpdate(rel, tuple,
   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           GetCurrentCommandId(false),
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
           scan->rs_cbuf);
           ~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
<builtin>: recipe for target 'pgrowlocks.o' failed
make[1]: *** [pgrowlocks.o] Error 1
make[1]: Leaving directory '/home/japin/greenplum-db/gpdb/contrib/pgrowlocks'
Makefile:102: recipe for target 'all-pgrowlocks-recurse' failed
make: *** [all-pgrowlocks-recurse] Error 2
```

This commit fix this bug.

### CODE REVIEW

**Comment by asimrp** [comment]
Thank you for the fix, @japinli.  Looks good to me.  Did you encounter a crash due to this problem?  Or is it a compiler warning that you are getting and want to fix?

**Comment by japinli** [comment]
@asimrp There is no crash because it cannot be compile with gcc 6.3.0.

File: contrib/pgrowlocks/pgrowlocks.c [hunk 1]
```diff
@@ -129,7 +129,7 @@ pgrowlocks(PG_FUNCTION_ARGS)
 		/* must hold a buffer lock to call HeapTupleSatisfiesUpdate */
 		LockBuffer(scan->rs_cbuf, BUFFER_LOCK_SHARE);
 
-		htsu = HeapTupleSatisfiesUpdate(rel, tuple,
+		htsu = HeapTupleSatisfiesUpdate(mydata->rel, tuple,
```
Comment (zhangh43) [inline contrib/pgrowlocks/pgrowlocks.c:132]: we should move the declaration `Relation rel;` into `if (SRF_IS_FIRSTCALL())` branch as well.

Comment (japinli) [reply contrib/pgrowlocks/pgrowlocks.c:132]: @zhangh43 Thanks for your advice! I have merged it.
