### ISSUE TITLE
Can't build with newer versions of Flex (2.6.4)

### ISSUE THREAD

**Issue by d** [greenplum-db/gpdb#4863]
### Greenplum version or build
master (b0333c5338 as of writing)

### OS version and uname -a
Ubuntu "bionic" (18.04 LTS)
`uname -a` output:
> Linux station2 4.15.0-15-generic #16-Ubuntu SMP Wed Apr 4 13:58:14 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### autoconf options used ( config.status --config )
`./configure --enable-debug --disable-orca --enable-cassert --enable-depend --with-libxml --with-perl --with-python --enable-mapreduce --with-zstd CFLAGS=-O0 CC='ccache gcc' CXX='ccache g++'`

### Installation information ( pg_config )
N/A because we can't build

### Expected behavior
That Greenplum compiles with newer toolchain

### Actual behavior
`make` failed to compile the parser with the following (redacted somehow error):
```
<builtin>: recipe for target 'gram.o' failed
gram.c:64:25: error: conflicting types for 'base_yylex'
 #define yylex           base_yylex
                         ^
scan.c:15262:12: note: in expansion of macro 'yylex'
 extern int yylex \
            ^~~~~
In file included from gram.y:62:0:
../../../src/include/parser/gramparse.h:66:12: note: previous declaration of 'base_yylex' was here
 extern int base_yylex(YYSTYPE *lvalp, YYLTYPE *llocp,
            ^~~~~~~~~~
gram.c:64:25: error: conflicting types for 'base_yylex'
 #define yylex           base_yylex
                         ^
scan.c:15265:21: note: in expansion of macro 'yylex'
 #define YY_DECL int yylex \
                     ^~~~~
scan.c:15286:1: note: in expansion of macro 'YY_DECL'
 YY_DECL
 ^~~~~~~
In file included from gram.y:62:0:
../../../src/include/parser/gramparse.h:66:12: note: previous declaration of 'base_yylex' was here
 extern int base_yylex(YYSTYPE *lvalp, YYLTYPE *llocp,
            ^~~~~~~~~~
make[3]: *** [gram.o] Error 1
common.mk:41: recipe for target 'parser-recursive' failed
make[2]: *** [parser-recursive] Error 2
```

### Toolchain information
```
jesse@jesusabs /w/gpdb (flex_2_6_4)> gcc --version
gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

jesse@jesusabs /w/gpdb (flex_2_6_4)> g++ --version
g++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

jesse@jesusabs /w/gpdb (flex_2_6_4)> flex --version
flex 2.6.4
jesse@jesusabs /w/gpdb (flex_2_6_4)> bison --version
bison (GNU Bison) 3.0.4
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```
